namespace: linode
name: cloud
version: 0.6.0
readme: README.md
description: Linode ansible collection
authors:
  - Luke Murphy (@decentral1se)
  - Charles Kenney (@charliekenney23)
  - Phillip Campbell (@phillc)
  - Lena Garber (@lbgarber)
license_file: COPYING
tags:
  - linode
  - cloud
repository: https://github.com/linode/ansible_linode
documentation: https://github.com/linode/ansible_linode/blob/v0.6.0/README.md
homepage: https://github.com/linode/ansible_linode
issues: https://github.com/linode/ansible_linode/issues
build_ignore:
  - '.gitignore'
  - '.github'
  - '.pylintrc'
  - '*.tar.gz'
  - 'Makefile'
  - 'template'
  - 'tests'
  - 'scripts'
