- name: Create an Object Storage key
  linode.cloud.object_keys:
    label: "provisioning-key-{{ ansible_date_time.epoch }}"
    state: present
  register: obj_key

- name: Get info about the desired cluster
  linode.cloud.object_cluster_info:
    region: us-east
  register: cluster_info

- name: Create an Object Storage bucket
  amazon.aws.s3_bucket:
    name: "{{ bucket_name }}"
    endpoint_url: "https://{{ cluster_info.clusters[0].domain }}/"
    aws_access_key: "{{ obj_key.key.access_key }}"
    aws_secret_key: "{{ obj_key.key.secret_key }}"

    state: present

- name: Upload the static site files
  amazon.aws.s3_object:
    endpoint_url: "https://{{ cluster_info.clusters[0].domain }}/"
    aws_access_key: "{{ obj_key.key.access_key }}"
    aws_secret_key: "{{ obj_key.key.secret_key }}"

    bucket: "{{ bucket_name }}"
    object: "{{ item | basename }}"
    src: "{{ item }}"
    mode: put
    permission: public-read
    ceph: true
  with_fileglob: 'roles/static_site/files/public/*.html'

- name: Configure the Object Storage Bucket as a website with index and error pages
  community.aws.s3_website:
    endpoint_url: "https://{{ cluster_info.clusters[0].domain }}/"
    aws_access_key: "{{ obj_key.key.access_key }}"
    aws_secret_key: "{{ obj_key.key.secret_key }}"

    name: "{{ bucket_name }}"
    suffix: index.html
    error_key: 404.html
    state: present

- name: Delete the Object Storage key
  linode.cloud.object_keys:
    label: "{{ obj_key.key.label }}"
    state: absent
  register: obj_key

- name: Print output
  debug:
    msg:
      - "Static Site Access URL: https://{{ bucket_name }}.{{ cluster_info.clusters[0].static_site_domain }}"
